### PR TITLE
Automated update

### PR DESCRIPTION
**Pull request by infinixbot**
<details><summary>cargo changes</summary>

### cargo upgrade

```
    Updating 'https://github.com/rust-lang/crates.io-index' index
    Checking nixpkgs-check-by-name's dependencies
name        old req compatible latest new req
====        ======= ========== ====== =======
lazy_static 1.4.0   1.5.0      1.5.0  1.5.0  
   Upgrading recursive dependencies
note: pass `--verbose` to see 9 unchanged dependencies behind latest
note: Re-run with `--verbose` to show more dependencies
  latest: 14 packages

```
### cargo update

```
    Updating crates.io index
    Updating proc-macro2 v1.0.85 -> v1.0.86
    Updating syn v2.0.66 -> v2.0.68
note: pass `--verbose` to see 11 unchanged dependencies behind latest

```
### cargo outdated

```
All dependencies are up to date, yay!

```
### cargo audit

```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 629 security advisories (from /home/runner/.cargo/advisory-db)
    Updating crates.io index
    Scanning repo/Cargo.lock for vulnerabilities (82 crate dependencies)

```
</details>
<details><summary>GitHub Action updates</summary>

</details>
<details><summary>npins changes</summary>

```
[INFO ] Updating 'nixpkgs' …
Changes:
-    url: https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre639552.e6cea36f8349/nixexprs.tar.xz
+    url: https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre642670.9693852a2070/nixexprs.tar.xz
-    hash: 0pii8c6wlh7wc6wxwhc85nyn3pk00qi3kn3jah2agf87cbmm9qdk
+    hash: 0742ps99c1nfqv2ahz0g964p38jyflzjpaxh7h7sjj847h0chiwg
[INFO ] Updating 'treefmt-nix' …
(no changes)
[INFO ] Update successful.
```
</details>

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
Looks good.

**Comment by philiptaron** [comment]
We do have a failing check: https://github.com/NixOS/nixpkgs-check-by-name/actions/runs/9647541224/job/26606586067?pr=74

> 2024-06-24T14:51:23.2958410Z + ./bin/xrefcheck
2024-06-24T14:51:23.2982638Z Configuration file not found, using default config for GitHub repositories
2024-06-24T14:51:23.2983436Z 
2024-06-24T14:51:33.3478677Z 
2024-06-24T14:51:33.3478692Z 
2024-06-24T14:51:33.3479367Z === Invalid references found ===
2024-06-24T14:51:33.3480468Z 
2024-06-24T14:51:33.3481071Z   ➥  In file README.md
2024-06-24T14:51:33.3482182Z      bad reference (external) at src:36:11-52:
2024-06-24T14:51:33.3483298Z        - text: "gzip"
2024-06-24T14:51:33.3484122Z        - link: https://www.gnu.org/software/gzip/
2024-06-24T14:51:33.3485238Z        - anchor: -
2024-06-24T14:51:33.3485832Z      
2024-06-24T14:51:33.3486512Z      ⛂  Response timeout

I think this is just gnu.org being super slow.

**Comment by philiptaron** [comment]
I did a do-nothing force push to get the checks to re-run.

**Comment by infinisil** [comment]
You should be able to re-run checks using the GitHub interface [here](https://github.com/NixOS/nixpkgs-check-by-name/actions/runs/9647541224/job/26606586067) :)

**Comment by philiptaron** [comment]
Thanks for letting me know.

**Pull request merged**
