### PR TITLE
Create a Nixpkgs PR after releases

### LINKED ISSUE #29: Automatically create a Nixpkgs PR when a new release is published
When an automated release happens using the [release.yml](https://github.com/NixOS/nixpkgs-check-by-name/blob/main/.github/workflows/release.yml) workflow, it would be really neat if it also created a PR against Nixpkgs to update its [pinned version](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test/check-by-name/pinned-version.txt).

The [automated update PR workflow](https://github.com/NixOS/nixpkgs-check-by-name/blob/65a04d8c47378684ecd4ef41c07fe8d1c34e480a/.github/workflows/update.yml) can be used as a reference for how to do that.

### PR DESCRIPTION
**Pull request by infinisil**
This should fix #29

---

This work is sponsored by [Antithesis](https://antithesis.com/) :sparkles:

### CODE REVIEW

**Comment by infinisil** [comment]
Basic tests indicate it works: https://github.com/tweag/nixpkgs/pull/89 :D

We are missing a changelog from our releases, but that could be done another time.

**Comment by willbush** [comment]
>We are missing a changelog from our releases

@infinisil Something to consider: https://git-cliff.org/
I've never gotten around to trying it personally

**Comment by infinisil** [comment]
@willbush Let's discuss that in https://github.com/NixOS/nixpkgs-check-by-name/issues/38 :)

**Comment by infinisil** [comment]
After testing it in https://github.com/tweag/nixpkgs/pull/90, I just moved it from the PR-triggered workflow file to the release-triggered one ([diff](https://github.com/NixOS/nixpkgs-check-by-name/compare/3ae4bb651586300fb3bece7a9ae9c999d02a55d8..a4a82e06eeddf4815cbea76ddac9a65076229d39)) (and added the `needs: release` and changed it to the NixOS/nixpkgs repo), so in theory it should work when this PR gets merged :)

**Review by willbush — APPROVED** [review]
Looks good!

**Review by philiptaron — APPROVED** [review]
I think it's so cool that a completely separate repository can initiate PRs to nixpkgs.

**Comment by infinisil** [comment]
Nice, it worked: https://github.com/NixOS/nixpkgs/pull/303140

Need to fix CODEOWNERS for me to get a ping though :) https://github.com/NixOS/nixpkgs/pull/303141

**Comment by philiptaron** [comment]
The codeowners file has errors:

image

**Comment by infinisil** [comment]
Not directly related, but feel free to fix it :)

**Comment by infinisil** [comment]
I'm guessing the "has write access to the repository" part

**Pull request merged**
