### PR TITLE
Fix automated updates (another try)

### PR DESCRIPTION
**Pull request by infinisil**
See https://github.com/NixOS/nixpkgs-check-by-name/pull/19#issuecomment-2013989023

### CODE REVIEW

**Review by philiptaron — APPROVED** [review]
# 🤖 
Let's see if this CI works better.

**Comment by infinisil** [comment]
Damn.. https://github.com/NixOS/nixpkgs-check-by-name/actions/runs/8382825696/job/22957369059

**Comment by infinisil** [comment]
Oh the problem now is that the script doesn't get run from the repo root lol

**Comment by infinisil** [comment]
Hopefully now.. https://github.com/NixOS/nixpkgs-check-by-name/pull/21

**Pull request merged**
