### PR TITLE
Automated update

### PR DESCRIPTION
**Pull request by infinixbot**
<details><summary>cargo changes</summary>

### cargo upgrade

```
    Updating 'https://github.com/rust-lang/crates.io-index' index
    Checking nixpkgs-check-by-name's dependencies
note: Re-run with `--verbose` to show more dependencies
  latest: 15 packages

```
### cargo update

```
    Updating crates.io index
    Updating proc-macro2 v1.0.84 -> v1.0.85

```
### cargo outdated

```
All dependencies are up to date, yay!

```
### cargo audit

```
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 628 security advisories (from /home/runner/.cargo/advisory-db)
    Updating crates.io index
    Scanning repo/Cargo.lock for vulnerabilities (82 crate dependencies)

```
</details>
<details><summary>GitHub Action updates</summary>

</details>
<details><summary>npins changes</summary>

```
[INFO ] Updating 'nixpkgs' …
Changes:
-    url: https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre631646.e2dd4e18cc1c/nixexprs.tar.xz
+    url: https://releases.nixos.org/nixpkgs/nixpkgs-24.11pre633168.6132b0f6e344/nixexprs.tar.xz
-    hash: 0mfb3ky0ylc5hlm9m1bzxy7r4p2j7g1mgh1ymwd94nd5m7gcl81b
+    hash: 0jli5364mw57krjc9csswc3xh1bvbjcv85hf81l9gx7fcp5qkswa
[INFO ] Updating 'treefmt-nix' …
Changes:
-    revision: 2fba33a182602b9d49f0b2440513e5ee091d838b
+    revision: 3eb96ca1ae9edf792a8e0963cc92fddfa5a87706
-    url: https://github.com/numtide/treefmt-nix/archive/2fba33a182602b9d49f0b2440513e5ee091d838b.tar.gz
+    url: https://github.com/numtide/treefmt-nix/archive/3eb96ca1ae9edf792a8e0963cc92fddfa5a87706.tar.gz
-    hash: 163ra7ck07maamg20ppqlsn8mjrf6jrn0g81334pvsfa1wr8g6n0
+    hash: 0g6cf61klla9zp50xwcfvi7m4ngni7wn6wwc5s7239ibsq6ilpdv
[INFO ] Update successful.
```
</details>

### CODE REVIEW

**Review by philiptaron — CHANGES_REQUESTED** [review]
We've got build problems!

**Comment by infinisil** [comment]
https://github.com/NixOS/infra/issues/438

**Comment by infinisil** [comment]
Perhaps the easiest local fix here is to switch to using the GitHub tarballs instead

**Comment by infinisil** [comment]
This should resolve itself soon now that https://github.com/NixOS/nixpkgs/pull/317122 is merged :)

**Pull request closed without merging**
